---
title: "Positive Hack Days 12"
---

# Рынок профессий ИБ. Как объяснить бабушке, чем ты занимаешься?

```         
Спикеры:
  Яна Юракова
  Евгений Миньковский
  Дмитрий Федоров
```

## Цитатки :)

> "Если у вас есть хоть какое-то высшее образование, то вы не пропадете" - Евгений Миньковский.

> "Чем раньше обнаруживается в программе баг, тем дешевле его купировать" - Евгений Миньковский.

> "Если в задаче нет решения это даже веселее ею заниматься" - Евгений Миньковский.

> "Безопасность - не конкретный программный продукт, а процесс, которым нужно непрерывно заниматься" - Евгений Миньковский.

> "Волшебник - компетенция, которая должна быть у ИБ-шника..." - Евгений Миньковский.

> "Аналитику **необязательно** знать, как выполнить ту или иную настройку. Но он должен знать, для чего ее необходжимо сделать - это доп. плюс!" - Яна Юракова

## Зачем получать высшее образование в сфере ИБ?

Спикер: Дмитрий Федоров

1.  Нетворкинг - создание и развитие сети полезных знакомств.

В ВУЗе вы можете пообщаться с преподавателями, студентами. Студенты - это будущие выпускники, которые потом будут вашими коллегами.

2.  Коммуникация - Умение договариваться

Договориться с преподавателями нужно об экзамене, о зачете. Все преподаватели разные и именно через это появляются навыки коммуникации.

3.  Фундаментальные знания

В ВУЗе студенты получают по операционным системам, компьтерным сетям, программированию, и которые также пригождаются в жизни.

4.  Кругозор - Философия, экономика, психология

В ВУЗах студенты узнают много про философию, экономику, психологию. А для чего? К примеру, психология нужна для понимания того, как мыслит злоумышленник, как он проникает в системы, что он думает при этом и т.п.

5.  Связь с работодателями

В области ИБ очень тяжело попасть на работу придя "с улицы". Поэтому, если вы отучились в высшем учебном заведении, то на 4-ом курсе приходит работодатель и интересуется студентами. Преподаватели могут советовать кого из студентов можно устроить.

### Как правильно выбрать ВУЗ в области ИБ?

1.  Наличие специальности ИБ в ВУЗе (бакалавриат/специалитет/магистратура/аспирантура)

2.  Преподаватели ВУЗа издают учебники и проводят научные исследования по темам ИБ

3.  ВУЗ сотрудничает с лидерами ИБ отрасли. Студенты проходят практику в ведущих компаниях

4.  ВУЗ обладает современным оборудованием и лабораториями

## Как объяснить бабушке, чем ты занимаешься?

Спикер: Евгений Миньковский

Внутри ИБ сообщества есть самые разные профессии:

-   Юристы
-   Аналитики
-   DevSecOps
-   Soc-оператор
-   Волшебник - компетенция, которая должна быть у ИБ-шника
-   и т.д.

Все эти специальности очень быстро меняются. Нормативная документация, которая требует чтобы появились те или другие специалисты, не успеавет за действительстью. И отсюда возникает вопрос: Есть ли в ИБ что-то более менее стабильное в перспективе 50-ти лет?

Ответ: Да.

На самом деле, ИБ люди занялись не так давно, но вообще - вопросы безопасности достаточно вечные. И по сей день, люди занимаются безопаснотью во многих отраслях. Отраслевая специфика, конечно же, есть, но вот подходы часто схожи. Как пример, проведем аналогию с безопаснотью дорожного движения.

Безопасность на дорогах:

Первым делом, занимаемся каким-то нормотворчеством - создаем какие-то требования к транспортным средствам, требования к дорогам и т.д. После этого проверяем эксплуатацию транспортных средств, занимаемся написание ПДД и другое. И далее будем производить контроль ПДД.

В принципе - точно такие же подходы работают и в IT.

1.  Нормотворчество в IT:

В даном аспекте будут востребавны люди с **юридической специальностью**, которые будут писать отраслевые нормативные акты (стандарты).

*Пример: VISA и MasterCard начинают разрабатывать свои стандарты PSI DSS.*

2.  Транспорные средства = Программное обеспечение(ПО)

Желательно разрабатывать это ПО так, чтобы в нем не было багов. Понятно, что когда баг вышел в продакшн, то ее пофиксить не всегда возможно. Чем раньше ты его обнаружишь, тем дешевле ее исправить.

Здесь в дело вступают **специальные инженеры**, которые работают по процессу Security, Development, Life-Cycle = цикл безопасной разработки. Эти инженеры помогают программистам в разработке ПО именно безопасным способом. Не просто рефакторинг - когда программисты собираются и начианют говорить друг другу "гадости", а именно на автоматизированнном уровне повышать культуру производства ПО.

3.  Эксплуатация транспортных средств = Эксплуатация ПО

На этом этапе возникают вопросы с возникновением процессов: процесс управления уязвимостями, мониторинг того, что происходит в сети

-   Процесс управления уязвимостями:

Специальные **аналитки** или **операторы спецализированных средств** начинают проверять, есть ли какие-то проблемы в сети -\> находят ПО с багами -\> прописывают айтишникам, что нужно сделать ("какие патчи нужно накатить") -\> айтишники накатывают патчи -\> аналитики смотрят на систему повторно - *Повторение этого цикла*

-   Мониторинг того, что происходит в сети

Смотрим какие собития бегут от конечных устройств -\> делаем вывод = нужен **аналитик**, чтобы сделать данный фундаментальный вывод.

*Пример: брутфорс*

## Кто такие аналитики ИБ?

Спикер: Яна Юракова

Когда мы смотрим площадки по поиску работы, мы обнруживаем кучу вакансий с описанием "аналитик", "аналитик ИБ (pintester)". Так кто же такой аналитк и в чем его работа?

### Навыки аналитика

1.  **Soft Skills - не связанные с профессией жизненные навыки**

-   Широкий кругозор

Если у вас появляется какая-то неожиданная проектная деятельность и необходимо знать какие-то особые специальные процессы.

-   Внимательность и усидчевость

Мы работаем с большими объемами данных и все это невозможно проанализировать без этого.

-   Коммуникативные навыки для сбора данных

Нужно уметь коммуникацировать с людьми, искать у них экспертизу, выспрашивать вопросы, чтобы разобраться в каких-то процессах.

-   Умение общаться с большим потоком информации

2.  **Hard Skills - профессиональные измеряемые данные**

-   Знание основ ИБ и нормативной базы

Без этого аналитиком в ИБ стать невозможно

-   Знание инструментов ИБ и средств защиты

Необходимо, чтобы рассказать, что можно сделать в том или ином случае.

-   Знание в сфере IT

Этот пункт больше про кругозор

-   Уверенный пользователь ПК, MS Office, MindMap и других программ и средств, упрощающих работу

Аналитику **необязательно** знать, как выполнить ту или иную настройку. Но он должен знать, для чего ее необходжимо сделать. Если знаем, это дополнительный плюс и мы уже в целом формируем какое-то представление о том, кто такой аналитик в ИБ.

### Примеры направлений для аналитиков ИБ

1.  **Анализ угроз ИБ**

Основные задачи - поиск полезных для исследований источников и их мониторинг, выявление трендов и наблюдение за ними

Функции:

-   Изучение форумов в дарквебе и телеграмм-каналов

-   Поиск новых ресурсов с информацией об уязвимостях, методах атак, инцидентах, вредоносном ПО и т.п.

-   Регулярное отслеживание трендов в инструментах и атаках злоумышленников

-   Сбор и анализ данных об угрозах ИБ для написания отчетов

Требуемые умения и навыки:

-   Знания и навыки работы в дарквебе

-   Навыки поиска и сбора информации, в том числе написания скриптов

-   Знания и навыки для анализа данных

-   Развитые коммуниативные навыки

2.  **Анализ событий в SOC**

3.  **Исследовательская деятельность**

Основная задача - проведение аналитических исследований

Цель исследований - помочь компаниям и обычным пользователям повысить свой уровень защищенности

Функции:

-   Проводить аналитические исследования

-   Взаимодействовать со СМИ в качестве эксперта ИБ

-   Проводить анализ защищенности отраслей, изучать деятельность группировок и работу вредоносного ПО

-   Делиться знаниями на конференциях и вебинарах

Требуемые умения и навыки:

-   Умение излагать мысли

-   Желание развиваться в сфере ИБ

-   Организованность и внимательность

-   Анализ и визуализация данных

-   Техническая база

4.  **Разработка методологий**

Методологи - **разрабатывают методики, инструкции**, которые можно легко внедрить. Эти методики помогают повысить общий уровень защищенности компаний.

Функции:

-   Создание фреймворка для легкого перехода к ИБ, работающей на результат

-   Разработка и написание методологий, методик, рекомендаций, инструкций

-   Написание статей и изучение материалов для общедоступного ресурса методологии результативного кибербеза

-   Построение и развитие сообщества ИБ специалистов

Требуемые умения и навыки:

-   Умение просто говорить о сложном

-   Внимательность и умение работать с большим объемом документов

-   Умение составлять специальные официальные документы

-   Широкий кругозор

5.  **Консалтинговые проекты**

Основная задача - **написание отчетов** по всем видам консалтинговых проектов: анализ защищенности, тестирование на проникновение и другие

Функции:

-   Выработка рекомендаций по безопасности. В том числе про устронение уязвимостей

-   Подготовка презентации по результатам проектов

-   Объяснение простым языком сложных схем атаки, техник, которые использовали пентестеры

-   Оценка критичности уязвимости и уровня защищенности систем

Требуемые умения и навыки:

-   Фундаментальные знания основ ИБ

-   Знание веб-уязвимостей и атак на внутренние сети (OWASP)

-   Скурпулезность и аккуратность

-   Развитые коммуникативные навыки

-   Опытный пользователь MS Office

-   Умение и желание обучаться новому

6.  **Проектная деятельность**

